test: "nosetests"
language: python
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - python setup.py install
python:
    - "2.7"
script:
    coverage run --source=code_reflector nosetests
